### ISSUE TITLE
minemention has problems with ftb teams

### ISSUE THREAD

**Issue by epicyeeto** [noeppi-noeppi/MineMention#4]
can't play with ftb teams
	Mod File: MineMention-1.16.4-0.1.8.jar
	Failure message: Minemention (minemention) has failed to load correctly
		java.lang.NoClassDefFoundError: com/feed_the_beast/mods/ftbteams/event/TeamDeletedEvent
	Mod Version: 1.16.4-0.1.8
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: com.feed_the_beast.mods.ftbteams.event.TeamDeletedEvent
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51] {}
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_51] {}
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_51] {}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:92) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-4.0.0.jar:?] {}
	at io.github.noeppi_noeppi.mods.minemention.compat.FTBTeamsCompat.init(FTBTeamsCompat.java:24) ~[?:1.16.4-0.1.8] {re:classloading}
	at io.github.noeppi_noeppi.mods.minemention.MineMention.<init>(MineMention.java:39) ~[?:1.16.4-0.1.8] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3123/1247570736.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3894/1360767433.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by noeppi-noeppi** [comment]
Which version of ftb teams?

**Comment by epicyeeto** [comment]
the lastest version
